# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jasper/CLionProjects/hyxWIP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jasper/CLionProjects/hyxWIP/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jasper/CLionProjects/hyxWIP/build/CMakeFiles /home/jasper/CLionProjects/hyxWIP/build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jasper/CLionProjects/hyxWIP/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hyx

# Build rule for target.
hyx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hyx
.PHONY : hyx

# fast build rule for target.
hyx/fast:
	$(MAKE) -f CMakeFiles/hyx.dir/build.make CMakeFiles/hyx.dir/build
.PHONY : hyx/fast

blob.o: blob.c.o

.PHONY : blob.o

# target to build an object file
blob.c.o:
	$(MAKE) -f CMakeFiles/hyx.dir/build.make CMakeFiles/hyx.dir/blob.c.o
.PHONY : blob.c.o

blob.i: blob.c.i

.PHONY : blob.i

# target to preprocess a source file
blob.c.i:
	$(MAKE) -f CMakeFiles/hyx.dir/build.make CMakeFiles/hyx.dir/blob.c.i
.PHONY : blob.c.i

blob.s: blob.c.s

.PHONY : blob.s

# target to generate assembly for a file
blob.c.s:
	$(MAKE) -f CMakeFiles/hyx.dir/build.make CMakeFiles/hyx.dir/blob.c.s
.PHONY : blob.c.s

common.o: common.c.o

.PHONY : common.o

# target to build an object file
common.c.o:
	$(MAKE) -f CMakeFiles/hyx.dir/build.make CMakeFiles/hyx.dir/common.c.o
.PHONY : common.c.o

common.i: common.c.i

.PHONY : common.i

# target to preprocess a source file
common.c.i:
	$(MAKE) -f CMakeFiles/hyx.dir/build.make CMakeFiles/hyx.dir/common.c.i
.PHONY : common.c.i

common.s: common.c.s

.PHONY : common.s

# target to generate assembly for a file
common.c.s:
	$(MAKE) -f CMakeFiles/hyx.dir/build.make CMakeFiles/hyx.dir/common.c.s
.PHONY : common.c.s

history.o: history.c.o

.PHONY : history.o

# target to build an object file
history.c.o:
	$(MAKE) -f CMakeFiles/hyx.dir/build.make CMakeFiles/hyx.dir/history.c.o
.PHONY : history.c.o

history.i: history.c.i

.PHONY : history.i

# target to preprocess a source file
history.c.i:
	$(MAKE) -f CMakeFiles/hyx.dir/build.make CMakeFiles/hyx.dir/history.c.i
.PHONY : history.c.i

history.s: history.c.s

.PHONY : history.s

# target to generate assembly for a file
history.c.s:
	$(MAKE) -f CMakeFiles/hyx.dir/build.make CMakeFiles/hyx.dir/history.c.s
.PHONY : history.c.s

hyx.o: hyx.c.o

.PHONY : hyx.o

# target to build an object file
hyx.c.o:
	$(MAKE) -f CMakeFiles/hyx.dir/build.make CMakeFiles/hyx.dir/hyx.c.o
.PHONY : hyx.c.o

hyx.i: hyx.c.i

.PHONY : hyx.i

# target to preprocess a source file
hyx.c.i:
	$(MAKE) -f CMakeFiles/hyx.dir/build.make CMakeFiles/hyx.dir/hyx.c.i
.PHONY : hyx.c.i

hyx.s: hyx.c.s

.PHONY : hyx.s

# target to generate assembly for a file
hyx.c.s:
	$(MAKE) -f CMakeFiles/hyx.dir/build.make CMakeFiles/hyx.dir/hyx.c.s
.PHONY : hyx.c.s

input.o: input.c.o

.PHONY : input.o

# target to build an object file
input.c.o:
	$(MAKE) -f CMakeFiles/hyx.dir/build.make CMakeFiles/hyx.dir/input.c.o
.PHONY : input.c.o

input.i: input.c.i

.PHONY : input.i

# target to preprocess a source file
input.c.i:
	$(MAKE) -f CMakeFiles/hyx.dir/build.make CMakeFiles/hyx.dir/input.c.i
.PHONY : input.c.i

input.s: input.c.s

.PHONY : input.s

# target to generate assembly for a file
input.c.s:
	$(MAKE) -f CMakeFiles/hyx.dir/build.make CMakeFiles/hyx.dir/input.c.s
.PHONY : input.c.s

updater.o: updater.c.o

.PHONY : updater.o

# target to build an object file
updater.c.o:
	$(MAKE) -f CMakeFiles/hyx.dir/build.make CMakeFiles/hyx.dir/updater.c.o
.PHONY : updater.c.o

updater.i: updater.c.i

.PHONY : updater.i

# target to preprocess a source file
updater.c.i:
	$(MAKE) -f CMakeFiles/hyx.dir/build.make CMakeFiles/hyx.dir/updater.c.i
.PHONY : updater.c.i

updater.s: updater.c.s

.PHONY : updater.s

# target to generate assembly for a file
updater.c.s:
	$(MAKE) -f CMakeFiles/hyx.dir/build.make CMakeFiles/hyx.dir/updater.c.s
.PHONY : updater.c.s

view.o: view.c.o

.PHONY : view.o

# target to build an object file
view.c.o:
	$(MAKE) -f CMakeFiles/hyx.dir/build.make CMakeFiles/hyx.dir/view.c.o
.PHONY : view.c.o

view.i: view.c.i

.PHONY : view.i

# target to preprocess a source file
view.c.i:
	$(MAKE) -f CMakeFiles/hyx.dir/build.make CMakeFiles/hyx.dir/view.c.i
.PHONY : view.c.i

view.s: view.c.s

.PHONY : view.s

# target to generate assembly for a file
view.c.s:
	$(MAKE) -f CMakeFiles/hyx.dir/build.make CMakeFiles/hyx.dir/view.c.s
.PHONY : view.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... hyx"
	@echo "... edit_cache"
	@echo "... blob.o"
	@echo "... blob.i"
	@echo "... blob.s"
	@echo "... common.o"
	@echo "... common.i"
	@echo "... common.s"
	@echo "... history.o"
	@echo "... history.i"
	@echo "... history.s"
	@echo "... hyx.o"
	@echo "... hyx.i"
	@echo "... hyx.s"
	@echo "... input.o"
	@echo "... input.i"
	@echo "... input.s"
	@echo "... updater.o"
	@echo "... updater.i"
	@echo "... updater.s"
	@echo "... view.o"
	@echo "... view.i"
	@echo "... view.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

